#!/bin/bash

source ../utils/utils.sh

docker-compose down -v
docker-compose up -d

KAFKA_1_IP=$(container_to_ip kafka-1)
KAFKA_2_IP=$(container_to_ip kafka-2)
KAFKA_3_IP=$(container_to_ip kafka-3)
KAFKA_4_IP=$(container_to_ip kafka-4)
interface=eth0

main() {
	sleep 20
	create_topic zookeeper-1 test 1 4 1
	sleep 5

	get_state zookeeper-1

	send_message kafka-1 'before network outage'
	read_messages kafka-1 1

	log 'Network outage starts'

	# rack A
	block_host kafka-1 $KAFKA_3_IP $KAFKA_4_IP
	block_host kafka-2 $KAFKA_3_IP $KAFKA_4_IP
	# rack B
	block_host kafka-3 $KAFKA_1_IP $KAFKA_2_IP
	block_host kafka-4 $KAFKA_1_IP $KAFKA_2_IP

	log 'Controller and partition leader should not be in the same DC'

	while : ; do
		leaderId=`get_state zookeeper-1 | tail -n1 | jq .leader`
		controlerId=`get_controller zookeeper-1 | tail -n1 | jq .brokerid`
		log "Leader $leaderId and controller $controlerId"
		[[ ($leaderId -le 2 && $controlerId -le 2)  || ($leaderId -gt 2 && $controlerId -gt 2) ]] || break
		force_reelection zookeeper-1
		sleep 5
	done

	send_message_from zookeeper-1 kafka-1 'after network outage via broker 1'
	send_message_from zookeeper-1 kafka-2 'after network outage via broker 2'
	get_state zookeeper-1
	
	send_message_from zookeeper-1 kafka-3 'after network outage via broker 3'
	send_message_from zookeeper-1 kafka-4 'after network outage via broker 4'
	read_messages_from zookeeper-1 kafka-$leaderId 10
	get_state zookeeper-1

	log 'Network outage ends'
	remove_partition kafka-1 kafka-2 kafka-3 kafka-4

	send_message_from zookeeper-1 kafka-$leaderId "after network outage ends - via broker $leaderId"
	read_messages_from zookeeper-1 kafka-$leaderId 10

	get_state zookeeper-1
}

main
